name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: 2.2.2

      - name: Detect version bump
        run: |
          # Check deno.json for new version, set environment variables if changed
          VERSION=$(jq -r '.version' deno.json)
          if [ "$VERSION" != "$(git describe --tags --abbrev=0 2>/dev/null || echo '0.0.0')" ]; then
            echo "VERSION_IS_UPDATED=true" >> $GITHUB_ENV
            echo "NEW_VERSION=$VERSION" >> $GITHUB_ENV
          fi

      - name: Publish package
        run: deno publish --allow-slow-types

      - name: Create tag and release
        if: env.VERSION_IS_UPDATED == 'true'
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ env.NEW_VERSION }}
          name: v${{ env.NEW_VERSION }}
          draft: false
          prerelease: false
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}
